language: go

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - tip

before_install: go get golang.org/x/tools/cmd/cover

install:
- go get github.com/Masterminds/glide
- glide install

script: go test -race -v -cover $(glide novendor)

env:
- GOMAXPROCS=8 GORACE="halt_on_error=1"

notifications:
  email: false
